dropchance: 50
books:
- Far to the southeast, there lies a wild unexplored peninsula, known to some as §9Monton§0.
- To the northwest is a lake, this gate hides below it's pristine surface. It is §9Umel§0.
- Hidden deep in a snowy forest in the north is §9Niveus§0.
- §9Hoogte§0 is where the tree canopy is so thick not even grass will grow on the ground.
- Wedged in a tight canyon not far from town, you will find §9Roko§0.
- On the coast of the sunny plains to the southeast, you will find §9Fungo§0.
- Recently found in a deep underground chasm, is §9Abismo§0.
- §9Selva§0 is a well known gate on the edge of a deep, dark jungle.
- In the plains of a wide savannah you can find §9Urbo§0.
- Found on a forested isle in the far northeast, you will find §9Lafo§0.