books:
- Far to the southeast, there lies a wild unexplored peninsula, known to some as §aMonton§0.
- To the northwest is a lake, this gate hides below it's pristine surface. It is §aUmel§0.
- Hidden deep in a snowy forest in the north is §aNiveus§0.
- §aHoogte§0 is where the tree canopy is so thick not even grass will grow on the ground.
- Wedged in a tight canyon not far from town, you will find §aRoko§0.
- On the coast of the sunny plains to the southeast, you will find §aFungo§0.
- Recently found in a deep underground chasm, is §aAbismo§0.
- §aSelva§0 is a well known gate on the edge of a deep, dark jungle.
- In the plains of a wide savannah you can find §aUrbo§0.
- Found on a forested isle in the far northeast, you will find §aLafo§0.
- Nothing to see here. Move along.